GET http://localhost:3000/tests

###

GET http://localhost:3000/tests/5e371b45568cf24260d66ada

###

POST http://localhost:3000/tests
Content-Type: application/json

{
    "title": "goose",
    "latitude": 44,
    "longitude": 66
}

###

DELETE http://localhost:3000/tests/5e3738acb4d2230a1db0d3ce

###

PATCH http://localhost:3000/tests/5e37313e5e309c07ad57bc60
Content-Type: application/json

{
    "title": "Tommy",
    "longitude": 100
}